### ISSUE TITLE
md-input closes the picker when the input gets focused

### ISSUE THREAD

**Issue by vinagreti** [ng2-ui/ng2-datetime-picker#100]
When using Material2 `<md-input>` the picker is closed just after I click the field because the field gets focused and then the picker closes because it looses the focus. 
A workaround is disable the field, so it doesn't gets focused and then the picker doesn't close. But than I do this, I need to click at the bottom line beyond the field to open the picker.
Are you planning to support material field?

See my code using disabled

```html
        <md-input 
        [(ngModel)]="sample.shipment_date" 
        ngControl="shipment_date" 
        name="shipment_date" 
        type="text" 
        placeholder="Shipment date" 
        [disabled]="true"
        ng2-datetime-picker
        date-format="DD/MM/YYYY hh:mm:ss"
        year="2014"
        month="12"
        day="31"
        hour="23"
        minute='59'
        close-on-select="true"
        ></md-input>
```

**Comment by allenhwkim** [comment]
I may add another feature to open datetime picker from any element including input field.
For an example, 
```
<input [(ngModel)]="myDate" />
<span class="glyphicon glyphicon-calendar" ng2-datetime-picker (valueChanged)="myDate=$event"></span>
```

**Comment by vinagreti** [comment]
Do you have any deadline for this?

**Comment by allenhwkim** [comment]
Just a plan at this moment
