### ISSUE TITLE
I updated ng2-datetime.js to have my stuff working

### ISSUE THREAD

**Issue by stefanaerts** [ng2-ui/ng2-datetime-picker#102]
Because in Ng2DateTimePickerDirective.normalizeInput
Ng2DateTime.parseDate is called without a dateFormat parameter
![image](https://cloud.githubusercontent.com/assets/3684599/21808001/9031601e-d741-11e6-9e25-31d560c33716.png)

I had to change NG2DateTime
![image](https://cloud.githubusercontent.com/assets/3684599/21808047/cb6a87d2-d741-11e6-8d79-3259e2ba0127.png)

I added an else{} when there is no dateFormat to send the date back with the default format 'YYYY-MM-DD HH:mm'

Please also update the documentation home page to YYYY-MM-DD HH:mm instead of YYYY-MM-DD HH:MM

**Comment by allenhwkim** [comment]
Thank you. I will update it later.
However, if you create a PR, the change will be much faster.

**Comment by stefanaerts** [comment]
I changed it local on my laptop,so i can continue.
I just wanted to share it with you guys because maybe it can help others.

Kind rg,
Stefan.
