### ISSUE TITLE
issue/feature to close the popup when you go outside the div

### ISSUE THREAD

**Issue by stefanaerts** [ng2-ui/ng2-datetime-picker#103]
Now i have to click within the div to close the popup.
How can i close the popup when i click outside the div?

**Comment by allenhwkim** [comment]
When you choose a date, it will close automatically.
![image](https://cloud.githubusercontent.com/assets/1437734/21810547/452d397a-d71a-11e6-942a-8d3ca98d59f1.png)

**Comment by stefanaerts** [comment]
Yes, but thats what i did not want,because then you have to click again to change the hour and minutes.So i put close-on-select=false.

**Comment by stefanaerts** [comment]
I could make the div having view hight 100% but then it does'nt look nice.
I wil try to find solution and let you know.

**Comment by stefanaerts** [comment]
solved:
I surrounded the div with another div having height:100vh
![image](https://cloud.githubusercontent.com/assets/3684599/21812459/4f756a90-d753-11e6-8ac7-b2715c9b0984.png)
