### ISSUE TITLE
question: how to trigger a standard html event on this component?

### ISSUE THREAD

**Issue by stefanaerts** [ng2-ui/ng2-datetime-picker#104]
How can i call a method when the popup is closed/value of the inputfield is changed wiht a new selected date?
So i want to update another variable with the date i get when selected.
methods like onchange="myfunction(this.value)" do not seem to work.
As you can see in the pciture below i want to update the label above with the new selected date
on close.
![image](https://cloud.githubusercontent.com/assets/3684599/21813407/693def26-d756-11e6-975c-fe37b403592c.png)

How can i do that?

**Comment by allenhwkim** [comment]
Currently it does fire `ngModelChange` event.
https://github.com/ng2-ui/ng2-datetime-picker/blob/master/src/ng2-datetime-picker.directive.ts#L49

**Comment by stefanaerts** [comment]
Thank you @allenhwkim for your fast responses.
It works nice with the (ngModelChange)="setTextValue($event)"
I have almost a nice progressive/mobile webapp finished with several nice features:
- payments with credit cards,paypal using braintree
- pickup and delivery possibilities
- checks automatically every x seconds if network is still up and gives mddialogs
- offline caching in browser
- material design using material2
- firebase data storage and security
- serverless (i use claudia) running program to connect with hosted fields on lambda(amazon)
- nice logging there also on lambda

And all of this for free, viva open source.

![image](https://cloud.githubusercontent.com/assets/3684599/21823092/ff95809c-d779-11e6-8b75-4c3e4e5dc522.png)

![image](https://cloud.githubusercontent.com/assets/3684599/21823136/2c7d2506-d77a-11e6-887d-6b3dde4a44de.png)

![image](https://cloud.githubusercontent.com/assets/3684599/21823154/38e56d1c-d77a-11e6-8014-88e0d8c64439.png)

![image](https://cloud.githubusercontent.com/assets/3684599/21823178/476cbd4a-d77a-11e6-8c0a-369f742ac161.png)
