### ISSUE TITLE
How can I select also Weekends day (Sat & Sun)?

### ISSUE THREAD

**Issue by mickeychu** [ng2-ui/ng2-datetime-picker#11]
I saw on the demo that weekends always are disabled. Is there anyway I can select these days?

And the demo on plunker doesn't work. Please check it again.

Thank you!

**Comment by allenhwkim** [comment]
Thanks for trying this module.

It works for me. I can select weekends too.
![image](https://cloud.githubusercontent.com/assets/1437734/17893216/e332e924-6912-11e6-9b57-7b06ead24452.png)

Is your environment different? e.g., Windows, IE11

**Comment by mickeychu** [comment]
thanks for your reply.
I tried again on Chrome and it worked ok but when I tried it on FireFox, it looks like this: 

![screen shot 2016-08-23 at 17 23 08](https://cloud.githubusercontent.com/assets/7807777/17895733/b44de0d4-6956-11e6-98a4-1c4c31fffe9f.png)

**Comment by allenhwkim** [comment]
windows env?

**Comment by allenhwkim** [comment]
I have pushed 0.5.6 with FF update, please test.
I have also tested with weekends, and it worked fine for me.

**Comment by mickeychu** [comment]
thank you for your update. I would like to ask which version will work with Angular2 RC4? (I still use RC4 for my current project.)

**Comment by allenhwkim** [comment]
This tag should work with RC4
https://github.com/ng2-ui/ng2-datetime-picker/tree/0.4.0

**Comment by mickeychu** [comment]
Updated to RC5 and it's working properly now, thank you!!!
