### ISSUE TITLE
Set template-driven form to dirty

### ISSUE THREAD

**Issue by rvdhooft** [ng2-ui/ng2-datetime-picker#117]
Currently, it looks like only dynamic forms are being set to dirty; it would be nice to support template-driven forms as well.

```
<form name="testForm" #testForm="ngForm">
        <input 
            name="testDate"
            [(ngModel)]="test"
            ng2-datetime-picker/>
</form>
testForm.dirty: {{testForm.dirty}}
```

**Comment by allenhwkim** [comment]
There is argument on this.
http://stackoverflow.com/questions/39681258/angular2-ng-dirty-class-is-not-set-when-ngmodel-value-changes

**Comment by rvdhooft** [comment]
Interesting. I'll go ahead and close this. Thanks.
