### ISSUE TITLE
close popup

### ISSUE THREAD

**Issue by Krisa** [ng2-ui/ng2-datetime-picker#12]
When we have a datetime, we must set close-on-select to false to let users time to select both a date and a time. But the only way to close the popup afterwards seems when clicking with the mouse somewhere outside the popup. It would be good to have other possibilities such as when Escape is clicked. Also when the blur event occurs on the input (through a tab for instance).

**Comment by allenhwkim** [comment]
Thanks for using this module.

Added Escape key.
Tried blur event, but was not successful.

**Comment by Krisa** [comment]
maybe blur event does not make too much sense after all. Because there are several input in the popup itself so it would be hard to monitor all of them ... 

Some additional ideas:
- an icon (X) or an "OK" button (or both) could also be there to help hiding the popup
- keyCode 13 (enter) may make sense too

**Comment by allenhwkim** [comment]
I am going to discuss more about this topic, which will not be implemented immediately.
