### ISSUE TITLE
ng2-datetime-picker.umd.js'

### ISSUE THREAD

**Issue by ltemimi** [ng2-ui/ng2-datetime-picker#126]
cannot find fins the above file ng2-datetime-picker.umd.js'

**Comment by allenhwkim** [comment]
It's in `dist` directory
https://github.com/ng2-ui/ng2-datetime-picker/blob/master/dist/ng2-datetime-picker.umd.js

**Comment by ltemimi** [comment]
Hi
I have found it in much older version. The latest version does not have it in the dist folder
thanks for your help
kind regards Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Tuesday, 31 January 2017, 16:59, Allen Kim <notifications@github.com> wrote:
 

 It's in dist directory
https://github.com/ng2-ui/ng2-datetime-picker/blob/master/dist/ng2-datetime-picker.umd.js—

**Comment by allenhwkim** [comment]
The latese version has it. Please check your environment

https://unpkg.com/ng2-datetime-picker@0.13.1/dist/ng2-datetime-picker.umd.js

**Comment by ltemimi** [comment]
Thanks Allen I will check
regards Laz ===================================Laz Temimi Automation & Control Engineer Tel.: 01733 810 068 Mobile: 07810 714 788 =================================== 

    On Wednesday, 1 February 2017, 14:44, Allen Kim <notifications@github.com> wrote:
 

 The latese version has it. Please check your environmenthttps://unpkg.com/ng2-datetime-picker@0.13.1/dist/ng2-datetime-picker.umd.js—
