### ISSUE TITLE
close on select, not interpreted

### ISSUE THREAD

**Issue by TwanoO67** [ng2-ui/ng2-datetime-picker#127]
Hello guys,

I'm trying to use the datetimepicker like that:

```
<input
	ng2-datetime-picker
	[close-on-select]="false"
	[ngModel]="myDate | timestampToDate:'DD/MM/YYYY [à] HH:mm:ss'"
       	(valueChanged)="changeMyDate($event)"
	[date-format]="'DD/MM/YYYY [à] HH:mm'"
 >
```

with my changed function like that:

```
private changeDateCreation(date, format='DD/MM/YYYY [à] HH:mm:ss'){
      moment.locale('fr');
      this.mydate = parseInt( moment(date,format).format('X') );
    }
```

It's all working well for the date transformation and all...

But the close-on-select parameter doesn't seem to be interpreted.
When I select a date or an hour etc... it always close the picker
then I have to re-open to select the hour
then reopen to select the minute etc...

What am I missing ?

**Comment by allenhwkim** [comment]
Please use like the following  as you see in README.md. The value is string "false", not boolean false.
`close-on-select="false"`

I treat this case as very exceptional, if that one does not satisfy your coding principal(true/false), please make a PR.

**Comment by TwanoO67** [comment]
I also tried with this syntaxe but it's not working neither.
Or at least, not how I expect it to...

Maybe it's not the option I am looking for, but for the moment, to select a date I have to:

- click on the input text, to open the datepicker
- select the date, that close the datepicker
- click on the input, to re open
- select the hour
- click on input, to re-open
- select the minutes, that close the datepicker
- done

So I supposed, that with the param "close-on-select" to "false", I would be abble to do:
- click on the input text, to open the datepicker
- select the date
- select the hour
- select the minutes
- then click outside the datepicker, to close (or maybe on a validation button ? )

Is that not what the option is for ?

**Comment by TwanoO67** [comment]
Ok, the problem was not in your code.

I was handling my own button to open the datepicker, and so on valueChanged, I closed the input myself.
The problem was that using the directive, with close-on-select we are unable to know if the valueChanged, or if the valueChanged and the popup was closed.
So I added an event to do that, and submitted a PR
