### ISSUE TITLE
How to add Calendar Icon using span tag

### ISSUE THREAD

**Issue by Antonystefano** [ng2-ui/ng2-datetime-picker#130]
This works fine. The datepicker is shown when I click span icon.
But how can I get the chosen date information?

`<span class="material-icons" ng2-datetime-picker>date_range</span>`

**Comment by allenhwkim** [comment]
Requirement is not clear. Please be more specific

**Comment by Antonystefano** [comment]
Thank you for touch.
This is my code.

```
<input [(ngModel)]="startDate" ng2-datetime-picker/>
<span class="material-icons" ng2-datetime-picker>date_range</span>
```

When I select the date on Input, the selected date would be shown in the Input.
But if I select the date by Span/Button, how can I get the selected date?
Thank you.

**Comment by allenhwkim** [comment]
Please take a look at this example from README.md
https://rawgit.com/ng2-ui/ng2-datetime-picker/master/app/index.html#/component-test

**Comment by Antonystefano** [comment]
Thank you.
It was solved.
Legend.
