### ISSUE TITLE
Trailing/leading days disabled for no reason

### ISSUE THREAD

**Issue by peterdeme** [ng2-ui/ng2-datetime-picker#131]
Hi,

We are having an issue where the trailing and leading days are disabled but they should not be.
Our use case: we are dinamically changing the `min-date` and `max-date` input like that: `min-date`: -15days from `default-value`, `max-date`: +15days from default value.
Now, for example. Let's say the default value is 2017 Feb 02. In this case is February month is open, then Jan 30 and Jan 31 is disabled in the date picker. If I go back to january, these dates are enabled.

I believe the issue is, that we need to call `selectable: !isDateDisabled(toDate(day))`, method in `monthData.leadingDays` as well as in case of `monthData.trailingDays`.

Thank you!
Peter

**Comment by allenhwkim** [comment]
please provide me a plunker example

**Comment by peterdeme** [comment]
https://plnkr.co/edit/pyuDFleDjuZyG6clzZdZ?p=preview

if you open the calendar, the januar dates are disabled.

**Comment by allenhwkim** [comment]
Oh..

You said
`The trailing and leading days are disabled but they should not be.`

But I think, 
`The trailing and leading days are disabled but they SHOULD  be.`

That's why it's gryed out as the same as disabled dates.

Do you think it should not?

**Comment by peterdeme** [comment]
Hi Allen,
Yeah, you are probably right, it makes sense to leave it disabled.
But one thing. What if, you click on the leading/trailing date and it will take you to that specific month?
Same approach as here:
https://nkalinov.github.io/ng2-datetime/
(if you click on leading January days, it will take you to January)

**Comment by peterdeme** [comment]
Thank you!
