### ISSUE TITLE
How can I show fullname of month?

### ISSUE THREAD

**Issue by Antonystefano** [ng2-ui/ng2-datetime-picker#132]
Hi.

<img width="244" alt="screen shot 2017-02-03 at 9 12 41 pm" src="https://cloud.githubusercontent.com/assets/24933056/22606826/911db9ce-ea55-11e6-8e40-013fdde5dcd8.png">

Now it shows "FEB 2017".
I want to change it "February 2017".

**Comment by allenhwkim** [comment]
Please update `Ng2Datetime.months`

https://github.com/ng2-ui/ng2-datetime-picker/blob/master/README.md#override-built-in-date-parser-and-date-formatter

```
[
    {fullName: 'January', shortName: 'Jan'},
    {fullName: 'February', shortName: 'Feb'},
    {fullName: 'March', shortName: 'Mar'},
    {fullName: 'April', shortName: 'Apr'},
    {fullName: 'May', shortName: 'May'},
    {fullName: 'June', shortName: 'Jun'},
    {fullName: 'July', shortName: 'Jul'},
    {fullName: 'August', shortName: 'Aug'},
    {fullName: 'September', shortName: 'Sep'},
    {fullName: 'October', shortName: 'Oct'},
    {fullName: 'November', shortName: 'Nov'},
    {fullName: 'December', shortName: 'Dec'}
  ]
```
You can make the fullname and shortName the same.
