### ISSUE TITLE
the date not bind to input field

### ISSUE THREAD

**Issue by sureshhustle** [ng2-ui/ng2-datetime-picker#134]
hi ,
    i had some problems on that date time picker.
    **it will not show the selected date in that input field**
![desctop screenshot](https://cloud.githubusercontent.com/assets/24749025/22704099/81c700f4-ed8c-11e6-8824-91c9d730b017.png)

**Comment by allenhwkim** [comment]
I assume that you used `date-format` without momentjs.
Please follow README.md related to moment js.

This will be closed by not following issue template.
