### ISSUE TITLE
Time-only picker cannot select current time

### ISSUE THREAD

**Issue by BaronChen** [ng2-ui/ng2-datetime-picker#135]
Plunker:
https://plnkr.co/edit/uPJp8PQiIr6rB4d5uL3v

**Current behavior**

  -   As seen in the above plunker, time-only picker cannot select default time.

**Expected/desired behavior**

  -  There should be a way for user to select current time

**Comment by allenhwkim** [comment]
It shows the current time in default.

![image](https://cloud.githubusercontent.com/assets/1437734/22721415/aaf798fc-ed7e-11e6-90eb-444b57ca680d.png)

**Comment by BaronChen** [comment]
Yes~

If the input box is empty, there will be no way for the user to set the input box value to the current time.

**Comment by allenhwkim** [comment]
I am just curious. I have never seen a requirement  to pick up current time.

what use case requuires to pick current time?

**Comment by BaronChen** [comment]
We are building a job scheduler and the user need to pick a earliest possible time for job to start.

**Comment by allenhwkim** [comment]
Oh.. you mean not display current time, but pick the current time.

**Comment by BaronChen** [comment]
Thank you very much, the fix works very well for us~
