### ISSUE TITLE
Time translation

### ISSUE THREAD

**Issue by enriquesomolinos** [ng2-ui/ng2-datetime-picker#137]
As you add the functionality of translating months and days, the time frame is not translatable. Labels "Time","Hour","Min" cannot be translated.

It's posible to add this strings like the months and days of the week ?

Thanks.

**Comment by allenhwkim** [comment]
Yes we can, but there are many ways to do it

1. Change HTML to css pseudo code, e.g. using `:before`, so that user can change css.
2. MomentJS has these terms? then make use of it
3. Accept parameter from user

Any suggestion?

**Comment by enriquesomolinos** [comment]
I think the best way to do this is following the same solution as you use for months and days labels:

  <span title="{{monthData?.fullName}}">
           {{monthData?.shortName}}
  </span>

You can do a little change like this:

  <span title="{{timeLabels?.title}}">
           {{timeLabels?.title}}
  </span>
  <span title="{{timeLabels?.hours}}">
           {{timeLabels?.hours}}
  </span>
  <span title="{{timeLabels?.minutes}}">
           {{timeLabels?.minutes}}
  </span>

As far as i know, momentjs hasn't this labels defined.

Thanks for all!

**Comment by allenhwkim** [comment]
@enriquesomolinos thanks, I will think about the suggested way.
