### ISSUE TITLE
Not able to start datetimepicker

### ISSUE THREAD

**Issue by LijinDurairaj** [ng2-ui/ng2-datetime-picker#141]
**ISSUE**  
i am new to angularJS 2 and i am trying to use date time picker, after downloading it, when i try to run using npm start, i am getting error.

**screen shot of the error** 
![capt1](https://cloud.githubusercontent.com/assets/24954803/22921788/11a6adbc-f2c1-11e6-927f-b9cc885b64ea.PNG)

**Comment by allenhwkim** [comment]
webpack-dev-server is not a recognized command

http://stackoverflow.com/questions/35810172/webpack-is-not-recognized-as-a-internal-or-external-command-operable-program-or
