### ISSUE TITLE
Is it supported internationalization and  localization?

### ISSUE THREAD

**Issue by gandra** [ng2-ui/ng2-datetime-picker#146]
Hi!
Congrats for great job!
I do not know where to ask question so I will throw it here. Does it have support for localization?

**Comment by allenhwkim** [comment]
Yes. It uses MomentJS for localization, and you can find French Example from README.md

**Comment by gandra** [comment]
Thanks!
I have seen french example but there are all english words?

**Comment by allenhwkim** [comment]
![image](https://cloud.githubusercontent.com/assets/1437734/23223664/a127610a-f8f9-11e6-8caa-2cc2cc480cbf.png)

This is not english

![image](https://cloud.githubusercontent.com/assets/1437734/23223689/b7df461a-f8f9-11e6-81be-af8965d734bf.png)

This is not english either.

**Comment by gandra** [comment]
Perfecto. Thanks.
Than only thi link in the readme is not valid. French example points to https://plnkr.co/edit/J6hXyB?p=preview which not exists. If you replacer https with http you get http://plnkr.co/edit/J6hXyB?p=preview and in this example there is no locale import.

But your screenshot is best answer! So I have to add `moment.locale('fr-ca')`.
Thanks!
