### ISSUE TITLE
How can I hide a minutes bar in date time picker to show only hours but not Minutes bar,Default Min should be zeros.

### ISSUE THREAD

**Issue by lakshmipunati** [ng2-ui/ng2-datetime-picker#147]
How can I hide a minutes bar in date time picker to show only hours but not Minutes bar,Default Min should be zeros.

**Comment by allenhwkim** [comment]
@lakshmipunati You can override css to hide it.

**Comment by allenhwkim** [comment]
Example: https://plnkr.co/edit/SBU98q?p=preview
