### ISSUE TITLE
'Current time' is not localized.

### ISSUE THREAD

**Issue by negberts** [ng2-ui/ng2-datetime-picker#153]
**Current behavior**
'Current time' is not localized. It is hardcoded in the css

```
.ng2-datetime-picker .select-current-time:before {
  content: 'current time';
  position: absolute;
  top: 1em;
  right: 5px;
  z-index: 1;
  cursor: pointer;
  color: #0000ff;
}
  
```

**Expected/desired behavior**
Content should be localized. For example via the static locale object. 

**Other information**

  -

**Comment by allenhwkim** [comment]
I will improve locale object later, but meanwhile, you can override css for your project.

**Comment by allenhwkim** [comment]
@negberts implemented and thanks for reporting this

**Comment by negberts** [comment]
Works!
