### ISSUE TITLE
Date format not working

### ISSUE THREAD

**Issue by kkarandikar0807** [ng2-ui/ng2-datetime-picker#154]
In my constructor I have a variable called testDate and I have initialized that as
`private testDate: Date = new Date();`
Now when I bind my input and give the property of date-format ="MM/DD/YYYY", it works perfectly fine. But, if I give a timeout and then do the same thing, the date format doesnt change.
**Current behavior**

  - Date format wont change on settimeout

**Expected/desired behavior**

  - Date format should change

**Other information**

  -

**Comment by allenhwkim** [comment]
It seems duplicate to https://github.com/ng2-ui/ng2-datetime-picker/issues/143
