### ISSUE TITLE
Error on manual entry of date (values out of range)

### ISSUE THREAD

**Issue by eromero90** [ng2-ui/ng2-datetime-picker#155]
When we type a date out of the range (months higher than 12 or days higher than 32) the datetime picker crashes

You can see the sreenshot, I'm using 50/08/2016

![image](https://cloud.githubusercontent.com/assets/7696588/23567394/abee1da8-001b-11e7-9644-6bbb017a0314.png)

**Current behavior**

  - The app throws an Exception and it invalidates the datetime picker

**Expected/desired behavior**

  - The component should manage out of the range values

**Comment by allenhwkim** [comment]
@eromero90 thanks for reporting this. I will take a look into it.

**Comment by Kurity** [comment]
After this fix got 'Cannot read property 'getTime' of null' error.

**Comment by allenhwkim** [comment]
@Kurity I don't see that error. Please provide me a plunker example.
