### ISSUE TITLE
Default date behavior

### ISSUE THREAD

**Issue by oryam** [ng2-ui/ng2-datetime-picker#158]
**Steps to reproduce and a minimal demo**

  - _What steps should we try in your demo to see the problem?_
Use the datepicker as provided examples.
  - _Plunker example_
https://ng2-ui.github.io/dist/#/datetime-picker
  - _If you cannot reproduce an issue with a plunker example, it's your environmental issue_
It is reproductible on your online demo.

**Current behavior**

  - I select a date in the calendar. Then I remove the text in the input field with backspace keyboard (not by selecting all the value than delete), then I focus out and focus the input. The calendar is shown at the date 1st Jan 1901 ("Jan 1")?
  - When using the default-value, it keeps opening the calendar on the default value, even if a date is already set. This behavior is strange, because when selecting a date, then editing it again, the user is expected to be on the current date of the input, not the default value.

**Expected/desired behavior**

  - The calendar should open the calendar at the today's date by default, or at the default date set if provided.
  - When using the default-date option, when the input has a value, the calendar should open on this value, not at the default date.

**Comment by allenhwkim** [comment]
@oryam thanks for reporting this. will be looked into.

**Comment by allenhwkim** [comment]
@oryam ng2-ui is behind the current version of ng2-datetime-picker. This will be fixed when ng2-ui is up-to-date. Please log this issue not at `ng2-ui/datetime-picker`, but at `ng2-ui/ng2-ui`

**Comment by oryam** [comment]
Ok. Thank you for your comment. I posted an issue https://github.com/ng2-ui/ng2-ui/issues/23

**Comment by allenhwkim** [comment]
My mistake, it is actually not related to version. it seems like a bug for this module.

**Comment by oryam** [comment]
Hello,

For information, the new condition `else if (dateStr.length > 4) {` and the default `else ` are never called if I am setting the `date-format` or/and `parse-format`.
Is it the expected behavior?

In my case, with using a date-format or/and parse-format, it would be great to have the calendar on the current date if the parsing failed.


```
<md-input-container class="fiw-input fiw-datepicker-right">
                <input mdInput 
                    formControlName="validityDate"
                    autocomplete="off"
                    maxlength="10"
                    ng2-datetime-picker
                    date-only="true"
                    date-format="YYYY/MM/DD"
                    parse-format="YYYY/MM/DD"
                >
            </md-input-container>
```

I have momentjs, to use `YYYY/MM/DD` pattern.
