### ISSUE TITLE
Empty default value gives error

### ISSUE THREAD

**Issue by negberts** [ng2-ui/ng2-datetime-picker#159]
There is a bug with defaultvalue on the latest package
The added line:

```
if(isNaN(this.defaultValue.getTime())) {

      this.defaultValue = new Date();

    }
```

fails when no default value is selected because this.defaultValue is null. So check should be

```
if(!this.defaultValue || isNaN(this.defaultValue.getTime())) {

      this.defaultValue = new Date();

    }
```

**Comment by allenhwkim** [comment]
@negberts thanks. This will be fixed soon

**Comment by negberts** [comment]
Works again
