### ISSUE TITLE
Localization possible?

### ISSUE THREAD

**Issue by mickeychu** [ng2-ui/ng2-datetime-picker#16]
Is this possible to localize the calendar using moment? Now it's displayed in English but I want to change it to Finnish, is this possible?

**Comment by allenhwkim** [comment]
Can you be more specific. e.g. week of days, month.  Are you talking about this popup?

![image](https://cloud.githubusercontent.com/assets/1437734/18096798/7fc88a1e-6ea9-11e6-8be0-91ceee69dcb2.png)

**Comment by mickeychu** [comment]
Yes, about the Months and Weekdays on this popup. I can manually change it on the source code but it would be great if it can be done by using moment :)

**Comment by allenhwkim** [comment]
Yes it is possible. any volunteer to make this work?

**Comment by allenhwkim** [comment]
Implemented this feature with 0.7.0.

**Comment by MartinNuc** [comment]
Is it possible to change the `Time`, `Hour` and `Min` label?
