### ISSUE TITLE
Issue #123 (formatted date when ngModel changes) reverted in 0.14?

### ISSUE THREAD

**Issue by Farplaner** [ng2-ui/ng2-datetime-picker#160]
It seems that issue #123 was reverted in commit listed here:
https://github.com/ng2-ui/ng2-datetime-picker/commit/932ec8768d3985ab1f4f1c66c553cbbc5c2546e2

With the code reverted, the issue happens again when the ngModel date changes externally, the date in the textbox does not get formatted.

**Comment by allenhwkim** [comment]
@Farplaner It is not reverted AFAIK. If you change `ngModel` by program, it does not change. This behaviour is never fixed(https://github.com/ng2-ui/ng2-datetime-picker/issues/143)

**Comment by Farplaner** [comment]
What I meant was, that this commit https://github.com/ng2-ui/ng2-datetime-picker/commit/bd23140910b5968bb7d777cd18f34a9ac4311ea1 is not found in the latest codebase.  It got lost between builds 0.13 and 0.14

See: https://github.com/ng2-ui/ng2-datetime-picker/blob/0.13.2/src/ng2-datetime-picker.directive.ts

Vs

https://github.com/ng2-ui/ng2-datetime-picker/blob/0.14.0/src/ng2-datetime-picker.directive.ts

(See ngOnChanges method)

**Comment by allenhwkim** [comment]
That line has been removed because of the refactoring.

https://github.com/ng2-ui/ng2-datetime-picker/commit/932ec8768d3985ab1f4f1c66c553cbbc5c2546e2#diff-a6d3452287aade41af42dca7a19fbb5aL152

**Comment by JayaniSumudini** [comment]
@allenhwkim I used ng2-datetime-picker and I want to closed it when I clicked on input box.I tried it by developing my code  using various types.Please give your kind regards to my problem.

**Comment by Farplaner** [comment]
Here's a plunkr that shows the problem: https://plnkr.co/edit/PcRGgUwSWk7XWcME0gt0?p=preview

When you click the button, the updated date is not formatted.

**Comment by allenhwkim** [comment]
@Farplaner thanks for it. It's duplicate issue of #143. I have tried and never fixed. Only thing you can do is to add `toString` method to your ngModel at this moment.

```
this.myDate.toString= () => Ng2Datetime.formatDate(myDate, `YYYY-MM-DD`)
```

**Comment by Farplaner** [comment]
I'm sorry that maybe I didn't get my intent across... but this commit https://github.com/ng2-ui/ng2-datetime-picker/commit/bd23140910b5968bb7d777cd18f34a9ac4311ea1 actually fixed the problem for me, but it was removed due to refactoring.

**Comment by allenhwkim** [comment]
OK, I will put that back and try, and check again.

**Comment by allenhwkim** [comment]
@Farplaner you were right, I made it back and tested and it worked.
Thanks for your patience.

**Comment by Farplaner** [comment]
Thank you for the fix.  I updated to the new 0.14.6 version and it works for me now.
