### ISSUE TITLE
Updated Plunkr

### ISSUE THREAD

**Issue by kibbled** [ng2-ui/ng2-datetime-picker#166]
Can we get an updated Plunkr example? The current one linked from the README uses old import of DateTime and is not compatible with the latest version. Also it would be nice if the example was more real world and defined the model property, initialized and all. Would avoid much confusion about how to use this framework.

**Comment by allenhwkim** [comment]
@kibbled thanks for reporting this. There was some wrong save on plunker, thus reverted back to 3 months ago version.

Updated plunker, https://plnkr.co/edit/su2aiL?p=preview
