### ISSUE TITLE
Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by sureshhustle** [ng2-ui/ng2-datetime-picker#167]
Hi,
   My date time picker display error when i close the picker after select date and time
i enclosed that screenshot please any one find out the solution for that.
![desctop screenshot](https://cloud.githubusercontent.com/assets/24749025/24042089/7c1ac3b2-0b36-11e7-828a-e3c057d039d4.png)

**Comment by allenhwkim** [comment]
@sureshhustle thanks for reporting this, but could you add a plunker example to reproduce this?

**Comment by dineshk16feb** [comment]
I am also facing same problem, its coming in your example plunker, it came only first time,

https://plnkr.co/edit/J6hXyB?p=preview

**Comment by allenhwkim** [comment]
Fixed
