### ISSUE TITLE
Delete/clear value

### ISSUE THREAD

**Issue by chrisbenseler** [ng2-ui/ng2-datetime-picker#172]
Is it possible to set a null/blank value to the datetimepicker?

Example, with this code:

<input
[(ngModel)]="publishdate"
ng2-datetime-picker
name="publishdate"
/>

if 'publishdate' has an date, user cannot delete the value from the input field. On the focus (click) of the input the datetimepicker opens.
I can add an extra button next to the input tha sets the publishdate do null, but is there anything built-in?

**Comment by allenhwkim** [comment]
I do not fully understand the problem you have. Could you explain with an example plunker?

**Comment by chrisbenseler** [comment]
@allenhwkim I could achieve what I needed (delete an value from the input after the selection of a date).
The problem is that if the input is on the footer of the page/browser, the datetimepicker opens above it, and then the user is not able to edit the input with the keyboard (pressind backspace/delete keys, for example).
Is it possible to force the position of the datetimepicker, to opens above the input?

**Comment by allenhwkim** [comment]
@chrisbenseler yes it is possible, but please create another issue with some screenshots for that after closing this.

**Comment by chrisbenseler** [comment]
I'll do it!
