### ISSUE TITLE
bundling @angular and rxjs with RC5 makes RC6 failing

### ISSUE THREAD

**Issue by Krisa** [ng2-ui/ng2-datetime-picker#18]
Because some dependencies have been updated as part of RC6 and ng2DatetimePicker is actually using RC5 in Npm, this module is breaking. 

Easy fix is to remove the package dependency (my current workaround was just to delete node_module in ng2DatetimePicker, npm defaults then on the main node_modules rep).

**Comment by visitek** [comment]
We use RC6 and everything is allright.

**Comment by allenhwkim** [comment]
closing. if not works, please open it again.
