### ISSUE TITLE
date-format doesn't work with banana in the box

### ISSUE THREAD

**Issue by visitek** [ng2-ui/ng2-datetime-picker#19]
<input #fromInput datetime-picker
            [(ngModel)]="from"
            close-on-select="false"
            date-format="DD.MM.YYYY HH:mm"
    >

while from value (ISO string) is changed in component, date-format is not applied and input contain ISO 2016-09-13T16:50:46Z instead of 13.09.2016 16:50

I should note that initialization and changing value from datepicker works fine. Only external changes don't touch formatting.

Probably bug

**Comment by allenhwkim** [comment]
` Only external changes don't touch formatting.`. Can you be more specific, or a plnuker?

**Comment by visitek** [comment]
yes, we should imlement OnChanges.. Directive does not know about @Input changes now

**Comment by visitek** [comment]
OnInit is not enough because picker could be already initialized while external event changes ngModel value. hm?

**Comment by visitek** [comment]
This component is not interactive now.. e.g.: I have DND area with setting time and opened datepicker should react on changes emmited by dnd. This is right banana in the box functionality in my opinion :)

**Comment by visitek** [comment]
Why do you use setTimeout? Ng2 has AfterViewInit and AfterViewCheck.. This module should be completely rewritten :(

**Comment by allenhwkim** [comment]
I heard. Could you make PR for it?

**Comment by visitek** [comment]
We've just forked it and will reimplement some blocks

**Comment by allenhwkim** [comment]
We always welcome your changes. It has been rewritten version from NG1 at this moment. It has some angular1 stuff. 
Please make PR from your forked version, or let me know your repo. I will borrow your codes :)

**Comment by visitek** [comment]
https://github.com/myappin/ng2-datetime-picker

**Comment by visitek** [comment]
We will create pull request while stable
