### ISSUE TITLE
Implement [WeekStartWith]

### ISSUE THREAD

**Issue by visitek** [ng2-ui/ng2-datetime-picker#21]
```js
@Input('week-start-with')
public weekStartWith:string = 'sun';
```

**Comment by allenhwkim** [comment]
This is already done by localization. Do you want to override localization?

**Comment by visitek** [comment]
ahh. I'll watch it later. It could be switchable manually.. from user
config for example

**Comment by visitek** [comment]
closed?

**Comment by allenhwkim** [comment]
Yes closed, won't do more than moments localization unless moments has a bug in it
