### ISSUE TITLE
Unexpected module 'Ng2DatetimePickerModule' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by smartm0use** [ng2-ui/ng2-datetime-picker#25]
I follow the installation steps but i get this error:

**Unexpected module 'Ng2DatetimePickerModule' declared by the module 'AppModule'**

Here is my `systemjs.config.js` and `app.module.ts`:

**systemjs.config.js**

    (function(global) {
        var map = {
            'app': 'app',
            '@angular': 'node_modules/@angular',
            'rxjs': 'node_modules/rxjs',
            'ng2-datetime-picker': 'node_modules/ng2-datetime-picker/dist'
        };

        var packages = {
            app: { main: 'main.js',  defaultExtension: 'js' },
            rxjs: { defaultExtension: 'js' },
            'ng2-datetime-picker': { main: 'ng2-datetime-picker.umd.js', defaultExtension: 'js' }
        };

        var ngPackageNames = [
            'core',
            'common',
            'compiler',
            'forms',
            'platform-browser',
            'platform-browser-dynamic',
            'http'
        ];

        function packIndex(pkgName) {
            packages['@angular/' + pkgName] = { main: 'index.js', defaultExtension: 'js' };
        }

        function packUmd(pkgName) {
            packages['@angular/' + pkgName] = { main: '/bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
        }

        var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;

        ngPackageNames.forEach(setPackageConfig);

        var config = {
            map: map,
            packages: packages
        };

        System.config(config);
    })(this);

**app.module.ts**

    import {NgModule} from '@angular/core';
    import {BrowserModule} from '@angular/platform-browser';
    import {FormsModule} from '@angular/forms';
    import {HttpModule, JsonpModule} from '@angular/http';

    import {AppComponent} from './app.component';
    import {Ng2DatetimePickerModule} from 'ng2-datetime-picker';

    @NgModule({
        declarations: [
            AppComponent,
            Ng2DatetimePickerModule
        ],
        imports: [
            BrowserModule,
            FormsModule,
            HttpModule,
            JsonpModule
        ],
        providers: [
        ],
        bootstrap: [AppComponent]
    })

    export class AppModule {
    }

**Comment by allenhwkim** [comment]
It should go to `imports` section.

**Comment by smartm0use** [comment]
Yes, you are right. Sorry.
Anyway during transpiling process i'm still get these errors:

`/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(24,14): error TS1005: '=' expected.
/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(24,18): error TS1005: ';' expected.
/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(25,14): error TS1005: '=' expected.
/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(25,19): error TS1005: ';' expected.
/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(26,14): error TS1005: '=' expected.
/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(26,17): error TS1005: ';' expected.
/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(27,14): error TS1005: '=' expected.
/myApp/node_modules/ng2-datetime-picker/dist/datetime-picker.component.d.ts(27,19): error TS1005: ';' expected.`

**Comment by allenhwkim** [comment]
The new error has been mentioned in issue #24, and will be dealt there.
