### ISSUE TITLE
ng-dirty is not triggered when date value has changed

### ISSUE THREAD

**Issue by cboissenin** [ng2-ui/ng2-datetime-picker#27]
Hello, 

First, thanks a lot for this useful component.

I'm using the datepicker within a model driven form :

`                <input class="form-control"
                       ng2-datetime-picker
                       formControlName="date_change"
                       date-only="true"
                       [(ngModel)]="crisisForm.value.status.date_change" />`

When a new value is selected, the class ng-dirty is not set to the input. Am i doing it wrong ?  
I've checked the demo and it look the same.

Thank you

**Comment by visitek** [comment]
do not use ngModel..it will be no longer supported because of encapsulation
of ngModel.

**Comment by allenhwkim** [comment]
I think we should get `ngModel` back to take advantage of Angular2 form elements.

https://angular.io/docs/ts/latest/guide/forms.html

If necessary,we need to have form controls too. I want users to take full advantage of angular2 built-in features.

**Comment by visitek** [comment]
No, look at ReactiveFormsModule. That's it. Simple FormModule is not
reactive and can not be used with formatting

**Comment by visitek** [comment]
whats you code? It works well :D

**Comment by visitek** [comment]
You can not emit broken(formatted) datetime from ngModel..it is not valid datetime and you can not work with it. It is for simple forms, but we are formatting output.. Can not use ngModel anymore

**Comment by visitek** [comment]
I found the way...
https://blog.ngconsultant.io/custom-input-formatting-with-simple-directives-for-angular-2-ec792082976#.c8g49yvmk

**Comment by Krisa** [comment]
definitely in support of ngModel, formControl, that's the standard way it works in Angular2. Whether it shall support an event emitter, it is probably just a "nice to have"...

**Comment by allenhwkim** [comment]
This will be fixed soon without using value and valueChange. FYI, the branch work in progress. https://github.com/ng2-ui/ng2-datetime-picker/tree/ngModel-enhanced

**Comment by allenhwkim** [comment]
This has been fixed with the release of 0.9.0. Please verify it is fixed. If not, let us know.

**Comment by Krisa** [comment]
I can't see it working. In previous version of the plugin, there was the valueChange output attribute, and it was possible to trick to make the form dirty by doing `(valueChange)="form.markAsDirty()" ` but `valueChange` is not triggered anymore.

**Comment by allenhwkim** [comment]
I think he is talking about `ng-dirty` class. `ng-dirty` class is set fine from the plunker example.
![image](https://cloud.githubusercontent.com/assets/1437734/18809216/395ecda0-8244-11e6-8a1f-33b5375d2626.png)

About value change part, please use `ngModelChange`, e.g.,  (ngModelChange)="myFunc($event)" which is recommended by Angular community.

**Comment by Krisa** [comment]
I see, thanks for the hint RE ngModelChange, this works now again.

Nonetheless regarding the main issue, if ng-dirty was triggered, I would expect that it shall also set the form to dirty.

**Comment by allenhwkim** [comment]
Yes it does set the form dirty.

**Comment by Krisa** [comment]
not that I can see: https://plnkr.co/edit/O5ARe7p1WBciHR68nADQ?p=preview

Look at the second input, `is dirty` stays also to `false` whatever you change in the input.

**Comment by allenhwkim** [comment]
You are right.

By some reason, ng-dirty is only set when you change the value manually. e.g., remove the value and visit it again.  However, I think this is angular behaviour I think.

![image](https://cloud.githubusercontent.com/assets/1437734/18810230/c1a6a7cc-825e-11e6-9e80-cf9e2e408424.png)

Any help would be appreciated for this matter. I don't seem able to make it possible setting `ng-dirty` by setting `ngModel` nor `value`.

**Comment by Krisa** [comment]
Never done that before, but maybe some inspiration can be found here: https://github.com/angular/angular/issues/11379#issuecomment-246756547

1- You specify formControlName as input parameter => you get the name of the control
2- You specify in the constructor the parent to get the ControlContainer
 => you can get the real control dynamically and then... set/patch the value without going through ngModel (this would solve another issue where we currently have to have both ngModel and formControlName specified). And it would solve implicitly automatically this issue.

Not sure it's best practice, or even working at all, but just an idea.

**Comment by allenhwkim** [comment]
It seems like an angular2 issue. I created a question at stackoverflow, https://plnkr.co/edit/C3Y4pE?p=preview, and let me see how it goes.

**Comment by Krisa** [comment]
I don't believe that it's valid to have both ngModel and formControl together. At least, it's the current workaround to have it working in this module, but normally it's either ngModel or formControl, not both together

**Comment by allenhwkim** [comment]
I don't think it matters to have both or not. "`ng-dirty` is not getting updated" in either cases.

**Comment by allenhwkim** [comment]
Based on the conversation, http://stackoverflow.com/questions/39681258/angular2-ng-dirty-class-is-not-set-when-ngmodel-value-changes?noredirect=1#comment66662757_39681258.
Community's response is that it's users' responsibility to make the input field dirty form input field if the value is set not by users' manual input but by functionality. e.g.,
`myForm.controls.myVar.markAsDirty()`

Thus closing this unless any new comes up.

**Comment by Krisa** [comment]
This does not make sense... because for this module, the user is not supposed to edit the input manually but to use the datepicker to set the date. Hence, this is the module which set the value in the input, and consequently, this shall be the module which makes the input dirty (by calling `myForm.controls.myVar.markAsDirty()`)

Based on the link I mentioned before, it's just about that I think
```
@Directive({
  selector: '......'
})
export class Ng2DatepickerComponent implements OnInit, OnChanges {
  constructor(
    @Optional() @Host() @SkipSelf() private parent: ControlContainer,
  ) { }

  @Input() formControlName: string;  
  private ctrl: AbstractControl;

  ngOnInit() { 
    if(this.parent && this.parent["form"]) {
      this.ctrl = (<FormGroup>this.parent["form"]).get(this.formControlName);
    }
  }

  ngOnChanges() {
      this.ctrl.markAsDirty();
  }
}
```

**Comment by allenhwkim** [comment]
Can you make PR with it?

**Comment by Krisa** [comment]
I must say, I have not exhaustively tested, but it seems to work with some basic examples.
