### ISSUE TITLE
How to keep the datetime-picker field without value (like a optional field)

### ISSUE THREAD

**Issue by celsoagra** [ng2-ui/ng2-datetime-picker#28]
Hi,

In my application, the date is a optional field, so I'd like to know if it is possible to define the field without any value.

Is it possible?

**Comment by allenhwkim** [comment]
It should be possible. If not, it should be a bug.

**Comment by celsoagra** [comment]
So, I just need to set my variable as null?
or is there a tag to do that?

here is my code on HTML file:
`<input type="text" maxlength="10" (valueChange)="onValueChange($event)" datetime-picker date-only="true" date-format="DD/MM/YYYY" [(ngModel)]="dateOptional" [ngModelOptions]="{standalone: true}" class="form-control" id="dateOptional">`

and in typescript file, I just set a null variable, as follows:
`public dateOptional = null;`

**Comment by visitek** [comment]
<input type="text" maxlength="10" (valueChange)="onValueChange($event)"
datetime-picker date-only="true" date-format="DD/MM/YYYY"
[value]="dateOptional" class="form-control" id="dateOptional">

But empty value is not supported yet.. Create issue

**Comment by celsoagra** [comment]
Thanks a lot!

**Comment by visitek** [comment]
mnt.. and see #27

**Comment by allenhwkim** [comment]
This will be fixed soon without using `value` and `valueChange`. FYI, the branch work in progress. https://github.com/ng2-ui/ng2-datetime-picker/tree/ngModel-enhanced

**Comment by celsoagra** [comment]
Thanks a lot!

**Comment by allenhwkim** [comment]
This has been fixed with the release of 0.9.0. Please verify it is fixed. If not, let us know.

**Comment by celsoagra** [comment]
Awesome. It works!
![img001](https://cloud.githubusercontent.com/assets/2061452/18765479/45dd5f1e-80ec-11e6-8dfc-4185f8f9dd82.jpg)

Thanks a lot!!
