### ISSUE TITLE
ng2-DateTime-Picker not working properly with Model Driven Forms

### ISSUE THREAD

**Issue by ramvilla** [ng2-ui/ng2-datetime-picker#30]
ng2-datetime-picker was working till we were on Template driven forms , but once we moved to the model driven forms we are unable to select the date and load that date into the input text box. (Calendar gets displayed when we hit the input text box and allows us to select dates but does not load that into the text field.)

Below is the code for the input textbox : 

```
 <input formControlName="blackoutDisplayBegin" [(value)]="blackout.DisplayBegin"
               datetime-picker  />
```

**Comment by allenhwkim** [comment]
Thanks for reporting this.
If possible, could you create a plunker for this?

**Comment by ramvilla** [comment]
You need a plunker with html and ts files and you will take care of importing node_modules package for the datetime-picker ? 

I am new to creating a plunker so not sure what are you looking for.

**Comment by visitek** [comment]
there is not emmiter on value now.. there is event called (valueChange)

**Comment by allenhwkim** [comment]
@visitek, FYI, next release will remove `value` and `valueChange` and take `ngModel` and `ngModelChange` back. lots of refactoring is going on my plate.

**Comment by visitek** [comment]
We fork it, it is no longer useful and interactive ;)

**Comment by visitek** [comment]
1) NgModel
[(ngModel)] ... input is passed into directive.. It is parsed and formatted. Formatted value is emitted into parent component.. WTF? formatted value is emitted?

2) Reactive
[value] is input and directive just listen on it. Value is formatted and rendered into input element. Date is kept and emitted with event name (valueChange).

In 1) parent component obtain wrong data, because it is formatted and it is not Date, but string without locale.
In 2) parent compoment listens on valueChange. It is real Date and it has nothing to do with formatted value.

Where is problem?

**Comment by visitek** [comment]
![image](https://cloud.githubusercontent.com/assets/1741839/18752865/009d4354-80e4-11e6-8cf2-9fb4597fe63e.png)
works fine with [(ngModel)] ... where is problem?

**Comment by ramvilla** [comment]
It works perfectly fine with the Template Driven Forms using  [(ngModel)]  as you mentioned , but doesn't work with the Model Driven forms where  [(ngModel)]  is not used and instead we use formControlName .

**Comment by visitek** [comment]
There is needed to keep all functionality approach.. can you give us code using modeldriven forms which doesn't work?

**Comment by visitek** [comment]
We can add formcontroll component into /app and debug model driven forms for it. But there is still problem with formatting and emitting diferent value..isn't there?

**Comment by allenhwkim** [comment]
This has been fixed with the release of 0.9.0. Please verify it is fixed. If not, let us know.

**Comment by ramvilla** [comment]
Thank You!!

 I will implement it in the way you mentioned and will update you how it goes.

**Comment by ramvilla** [comment]
I see a compilation error with the newer version of the datetime-picker i.e. 0.9.1
The error is in the class : datetime-picker-component.d.ts
