### ISSUE TITLE
Deprecation warning ....

### ISSUE THREAD

**Issue by Krisa** [ng2-ui/ng2-datetime-picker#31]
I experience the same issue, than the one we can see in the plunkr of this Readme (just open the console): https://plnkr.co/edit/su2aiL?p=preview

Not sure what the issue is about though.

**Comment by allenhwkim** [comment]
Those ones are warning about momemtjs and normal date. I only use MomentJS only if available. However, momentjs does not want to use Date if momentjs is used. I tried to turn it off, but was not successful.

**Comment by allenhwkim** [comment]
This annoying warning has been removed by following this http://stackoverflow.com/questions/23263380/deprecation-warning-moment-construction-falls-back-to-js-date
