### ISSUE TITLE
moment.js supports typescript

### ISSUE THREAD

**Issue by Krisa** [ng2-ui/ng2-datetime-picker#32]
Adding the moment.js script directly in the html page is probably an unusual way for Angular2 developers using typescript. Additionally, Moment.js supports typescript (http://momentjs.com/docs/#/use-it/typescript/) so it would be probably easy to support that in this module

**Comment by allenhwkim** [comment]
I ran out of idea now. Could you make a PR for this? I would appreciate if you do

**Comment by allenhwkim** [comment]
Tried moment with typescript
However, IMO, momentjs is not ready for Typescript and webpack.
I will close this until someone successfully use momentjs in typescrpt and webpack.
