### ISSUE TITLE
Calendar not picking the date set in the input

### ISSUE THREAD

**Issue by Krisa** [ng2-ui/ng2-datetime-picker#33]
As shown on the plunkr of the Readme https://plnkr.co/edit/su2aiL?p=preview, when clicking on the link "2015-06-30", the date is set correctly. However, when opening the popup, it opens to the date of today.

**Comment by allenhwkim** [comment]
Thanks for reporting this. I will take a look at it

**Comment by allenhwkim** [comment]
fixed and released as 0.9.1. Please verify the fix.

**Comment by Krisa** [comment]
This seems to work, thanks
