### ISSUE TITLE
Empty value

### ISSUE THREAD

**Issue by luizfbicalho** [ng2-ui/ng2-datetime-picker#34]
Is there a way that I can use the datepicker and set an empty value

It would be interesting to have a property allow null and them have a button to set the date value null.

**Comment by allenhwkim** [comment]
It's input field. You can set as blank. Does it have to be null?

**Comment by luizfbicalho** [comment]
If I hit backspace I get an error,  and i get invalid date, after that, the date picker doesn't show any value

![image](https://cloud.githubusercontent.com/assets/16882855/18809726/198ffeb6-825a-11e6-919c-1c51fb3da980.png)

**Comment by allenhwkim** [comment]
Ok this is a bug then. I will make a fix soon

**Comment by luizfbicalho** [comment]
thanks a lot

**Comment by allenhwkim** [comment]
I tried to reproduce this one, however failed. I think you are looking at something different url, e.g., ng2-ui.github.io. , which is no up-to-date.
Please test the given plunker in README.md,  https://plnkr.co/edit/su2aiL, and make it sure this is reproducible.

**Comment by luizfbicalho** [comment]
I had some compilation problems using the npm, so I put the source in my project

This way I might be outdated

**Comment by allenhwkim** [comment]
closing this. Please reopen the issue if problem still exists.
