### ISSUE TITLE
angular 2 final intergration?

### ISSUE THREAD

**Issue by mickeychu** [ng2-ui/ng2-datetime-picker#37]
How to make this work with Angular 2 final (2.0.1) ? thank you!

**Comment by allenhwkim** [comment]
README.md install instruction does not work with 2.0?

**Comment by mickeychu** [comment]
I works, but it cause these warning: 

![screen shot 2016-09-27 at 16 26 39](https://cloud.githubusercontent.com/assets/7807777/18875651/49ec99b2-84cf-11e6-8001-4b90a583ce9b.png)

Besides, it made my form always Dirty from the beginning, even I have set it to Pristine.

**Comment by allenhwkim** [comment]
Thanks for reporting this. I will treat as bug.

**Comment by allenhwkim** [comment]
@krisa, can you look into this issue?

**Comment by Krisa** [comment]
@mickeychu - the latest PR shall have resolved that. 

But you should remove `blur` and `ngModel` because I think there is some conflicts here.
```
<input type="text" formControlName="deadlineDate" ng2-datetime-picker close-on-select="false" date-only="true">
```
@allenhwkim I think the Readme is slightly outdated too in this regard (it references both ngModel and formControl)

**Comment by allenhwkim** [comment]
https://plnkr.co/edit/su2aiL?p=preview
![image](https://cloud.githubusercontent.com/assets/1437734/18880716/daee7850-84a6-11e6-94c7-64d7ee70cd7a.png)

I have tested this plunker without ngModel, but it seems never makes the form dirty by selecting a date. With ngModel, it makes form dirty initially.

**Comment by Krisa** [comment]
This works when clicking on a link, but selecting a date is not triggering the markAsDirty method ... will check later today

**Comment by allenhwkim** [comment]
thanks @Krisa

**Comment by Krisa** [comment]
there is something weird with all these messages. but the PR looks normal.

**Comment by mickeychu** [comment]
I've updated the package to latest release 0.9.5. Removed the ngModel. The form is not Dirty when the page first loaded. 

However, when I change the date and submit the form, the value of the date does not change at all. (though it does change the date displayed on the input)

**Comment by Krisa** [comment]
Yes, the package has not been updated on Npm yet. Can you try with the github version instead?

**Comment by mickeychu** [comment]
Oh yes, it works perfect now. Thank you @Krisa . Will you update the npm package soon?

**Comment by Krisa** [comment]
@allenhwkim is the Npm master!

**Comment by allenhwkim** [comment]
This should be on npm. 0.9.6 matches to the current github master branch.
