### ISSUE TITLE
Compatibility with bootstrap

### ISSUE THREAD

**Issue by Gillardo** [ng2-ui/ng2-datetime-picker#41]
The wrapper element which has a className of `ng2-datetime-picker` has a style added to it for inline-block.

All input controls by default are 100% of the container control.  If using this control with bootstrap, you can a result like this

![image](https://cloud.githubusercontent.com/assets/7406381/18992901/a936ed8c-8718-11e6-84ee-ffd763257f55.png)

But if you remove the display: inline-block, it appears full width correctly.  Any reason for this??

**Comment by allenhwkim** [comment]
Since I do not use bootstrap, I do not fully understand this issue.
Please create a plunker example for this issue, or else it will take a long time for me to understand what's going on.

**Comment by matteosuppo** [comment]
Gilardo is asking what's the reason for giving an inline-style `{display: 'inline-block'}` to the wrapper `.ng2-datetime-picker`

It messes up templates (not only with boostrap) because it's not easily modifiable

**Comment by Gillardo** [comment]
Exactly that!

**Comment by allenhwkim** [comment]
ok. I will try removing 'inline-block' and see how it goes

**Comment by Krisa** [comment]
The commit shall resolve the issue

**Comment by guyspronck** [comment]
I'm re-opening this issue as it is not really resolved. I'm unable to overwrite the display because the template loads the css, after my css is loaded, thus overwriting my custom value. I don't see why the inline-block is there at all. It seems like it's not required and it only messes with custom styles.

**Comment by allenhwkim** [comment]
@guyspronck please make your css more specific than the template. e.g., 
```
.my-class .ng2-datetime-picker {
    display: inline-block;
    position: relative;
}
```

@Krisa could you try removing `inline-block`

**Comment by guyspronck** [comment]
@allenhwkim I have solved the issue by having an !important flag on the CSS in my master styling file, but this isn't the best way to solve this.
