### ISSUE TITLE
Fill field don't propagate to component

### ISSUE THREAD

**Issue by odisi** [ng2-ui/ng2-datetime-picker#44]
When I type a date in the input like 01/01/2010, the value don't propagate to component.

Somebody have the same problem?

Somebody can help me?

The input code follow:

```
<input class="mdl-textfieldcustom__input ng-valid ng-touched ng-dirty" date-format="DD/MM/YYYY" date-only="true" ng2-datetime-picker="" type="text" ng-reflect-model="" ng-reflect-date-format="DD/MM/YYYY" ng-reflect-date-only="true" ng-reflect-ng-model="" ng-reflect-id="de" id="de" ng-reflect-read-only="false">
```

**Comment by allenhwkim** [comment]
@Krisa can you take a look at this issue?

**Comment by Krisa** [comment]
I've noticed this problem too since quite some time. The input is cleared for some reasons when the input is blurred. Will look at it if I find the cause.
