### ISSUE TITLE
Datepicker shall be updated in "real-time" when ngModel / formControl is changed manually

### ISSUE THREAD

**Issue by Krisa** [ng2-ui/ng2-datetime-picker#50]
Follow up of https://github.com/ng2-ui/ng2-datetime-picker/pull/46#issuecomment-252666624

**Comment by allenhwkim** [comment]
Is this really necessary? Unless the implementation is very simple, I would against it.
Hope we find a very simple solution for it.

**Comment by Krisa** [comment]
yep, the PR solves the problem.
