### ISSUE TITLE
DatePicker doesn't close

### ISSUE THREAD

**Issue by odisi** [ng2-ui/ng2-datetime-picker#52]
When focus is in DatePipcker like when month is changed and date isn't selected and the focus is changed to other input using tab, datepicker doesn't close.

**Comment by Krisa** [comment]
this one could be tricky because we cannot hide the datepicker when the input is blurred (otherwise it would close the datepicker for every click on the datepicker). Meaning that we would have to listen for a focus event for anything on the page... but the input of the datepicker.

**Comment by allenhwkim** [comment]
Until we have a simpler solution for this, I will close this as 'won't fix'.
