### ISSUE TITLE
Model as Date when format is used

### ISSUE THREAD

**Issue by luizfbicalho** [ng2-ui/ng2-datetime-picker#54]
I made this plunkr
https://plnkr.co/edit/yOoXEdAeVqUvlElVN32Q?p=preview
if I put a Date object, it shoudn't return the date object back?

the displayed value should be the formatted and the internal value should be the date correct?

**Comment by allenhwkim** [comment]
It returns date object back with `toString` function overwritten.

https://plnkr.co/edit/FNSFdcRfx5HeCDgjySGJ?p=preview
