### ISSUE TITLE
Feature Request: "Snap Time" option

### ISSUE THREAD

**Issue by LukeHartcher** [ng2-ui/ng2-datetime-picker#58]
A nice feature would be to be able to "snap" the time scroll bar to a given minute period e.g. if "time-snap=10" then the time slider would snap to 0/10/20...50.

User feedback is that the time can be a bit fiddly to use and most times people want either a 5 or 10 or 30 minute selection.

Just a thought. Keep up the great work! :)

**Comment by allenhwkim** [comment]
Do you mean step of minute as in here, https://www.w3.org/wiki/HTML/Elements/input/range?

**Comment by allenhwkim** [comment]
added 'minute-step' as an attribute value
