### ISSUE TITLE
Installing with angular-cli/webpack

### ISSUE THREAD

**Issue by pdeason** [ng2-ui/ng2-datetime-picker#59]
Hi, I am trying to install the timepicker with an angular-cli/webpack project so am unable to edit the system.config.js directly as in the instructions:

> map[‘ng2-datetime-picker'] = 'node_modules/ng2-datetime-picker/dist';
>  packages[‘ng2-datetime-picker'] = { main: 'ng2-datetime-picker.umd.js', defaultExtension: 'js’ }

I have implemented the other steps but am unable to get the timepicker appearing. Could you kindly advise whether I would need to take alternative steps to map in this environment? I would be grateful for any help you may be able to give. Many thanks!

**Comment by allenhwkim** [comment]
Hmm, I thought this line can make webpack compatible.

https://github.com/ng2-ui/ng2-datetime-picker/blob/master/package.json#L7

**Comment by allenhwkim** [comment]
I have tested with webpack and it seems working fine for me. Please verify the change.

**Comment by pdeason** [comment]
Hi, my apologies, it seems the issue was coming from one of the dependencies and a JQuery version it required, which was conflicting with anther package. However, this now seems to work fine. Thank you for your help.
