### ISSUE TITLE
Date and Time becomes NaN when user tries to use keyboard to change date time value instead of picker

### ISSUE THREAD

**Issue by sreeneshkini** [ng2-ui/ng2-datetime-picker#60]
Hello, This is Sreenesh Kini. I am facing some issue in using this datetimepicker....When I try to edit the date or time from input box using keyboard, without using the picker, then it gives me error as "NaN". I am attaching the screenshots here..
![error](https://cloud.githubusercontent.com/assets/7059958/19757044/5525581a-9c3e-11e6-8486-46bfec9a905e.PNG)

Please help for a solution. Thank you.

**Comment by allenhwkim** [comment]
Here is the plunker

https://plnkr.co/edit/jb2rh5?p=preview

We will make a fix soon.

**Comment by allenhwkim** [comment]
This seems fixed. Please make it sure the change is correct.
