### ISSUE TITLE
defaultValue

### ISSUE THREAD

**Issue by NaLLiFFuNT** [ng2-ui/ng2-datetime-picker#63]
Could you add ability to add default value.
By default if you open picker you see current date & time.

**Comment by allenhwkim** [comment]
I thought this is already there by adding year, month, date, hours, minutes. https://github.com/ng2-ui/ng2-datetime-picker/blob/master/README.md#usage-it-in-your-code

**Comment by allenhwkim** [comment]
Hmm, I thought it was working, https://plnkr.co/edit/k5fw7S?p=preview, but it seems not.

@NaLLiFFuNT we better to fix this as required rather than having a fixed default value. It makes fix only some values not all of them, year, month, day, hour, or minute.

**Comment by NaLLiFFuNT** [comment]
I tried this way. But it didn't work to me.
Also, i think the way passing one param instead of passing five params is more convenient

**Comment by NaLLiFFuNT** [comment]
anyway default value is NOW. if you create a Date object, default value is NOW. if you use moment, default value is NOW too. You can easily modify initial date with momentJS, which your component is required.

**Comment by allenhwkim** [comment]
I may miss something https://gitter.im/ng2-ui/ng2-datetime-picker?utm_source=share-link&utm_medium=link&utm_campaign=share-link
can we talk about it here?

**Comment by allenhwkim** [comment]
@NaLLiFFuNT you can pre-fill the value with [(ngModel)]. That makes I feel [defaultValue] is redundant to `ngModel` except it prefills the input field.

**Comment by NaLLiFFuNT** [comment]
I talked about value which picker shows, before you select any value
