### ISSUE TITLE
Including datetime-picker directive in bootstrap tab content causes page refresh on tab click

### ISSUE THREAD

**Issue by pratts** [ng2-ui/ng2-datetime-picker#65]
Hello,
I recently tried using ng2-datetime-picker and I am currently using bootstrap also. There are two tabs and one of them contains a form containing elements that uses datetime-picker. When I click on any tab, page refreshes. When I remove 'datetime-picker', tabs work.

**Comment by allenhwkim** [comment]
Please create a simple plunker example to recreate your issue, so that we can debug it

**Comment by pratts** [comment]
[Plunker Example](https://embed.plnkr.co/ISqR3z3ocMRoCJkyOWhv/)

This is the plunker I could create. In the div with id profile, an input is included that uses ng2-datetime-picker. When plunker is run, tabs do not work. When I remove the input or the ng2-datetime-picker directive, tabs work.

When I downloaded the plunker and tried to run it on my system, page refreshes whenever I try to change the tab (same as problem mentioned above).

Thank you

**Comment by allenhwkim** [comment]
@pratts thanks for your example, I will look into it

**Comment by allenhwkim** [comment]
Very strange, I believe that bootstrap tab does not allow the change of contents. It will take a long time to debug this if I want to make it correct because it might be only fixable by bootstrap.

I tried ng2-tab, and it all worked fine for me.

https://plnkr.co/edit/X0j5wIEKyuH0ezlKp9rr?p=preview

**Comment by pratts** [comment]
I tried to look into the code and tried to comment the line:
document.body.addEventListener('click', this.hideDatetimePicker);
in the file src/date-time

**Comment by pratts** [comment]
Commenting the below mentioned line in hideDatetimePicker function and uncommenting line mentioned above also works:
event && event.stopPropagation();

**Comment by allenhwkim** [comment]
@pratts Thanks, could you make PR for that?

**Comment by pratts** [comment]
Hello @allenhwkim,
Commenting the above mentioned lines causes the hideDatetimePicker function to run multiple time (earlier it was handled by stopPropagation), although it seemed that it was not creating any problems.

Will it be alright to make a PR of that line commented ?

**Comment by allenhwkim** [comment]
@pratts can you make to run hidedatimepicker ton run only 1 time using a variable?  E.g if hidden already do not run it

**Comment by pratts** [comment]
Hello @allenhwkim , I will try and send a PR. It will take some time.
Thank you for your help.

**Comment by allenhwkim** [comment]
@pratts, thanks for trying my idea. LMK if it does not work
