### ISSUE TITLE
AOT support 

### ISSUE THREAD

**Issue by msaccone** [ng2-ui/ng2-datetime-picker#67]
Hi @allenhwkim, great work so far :)

Could u please add support for AoT compiler ??

**Comment by allenhwkim** [comment]
@msaccone Thanks for your feedback.
I do not know much about `AoT`.  Any help would be appreciated.

**Comment by msaccone** [comment]
I'm not sure how to achieve it. At first glance you u should add a metadata.json for your *.d.ts files
Take a look into this article
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.yohi2g52v
