### ISSUE TITLE
 TypeError: Cannot read property 'fullName' of undefined

### ISSUE THREAD

**Issue by neelsbr** [ng2-ui/ng2-datetime-picker#7]
#<img width="187" alt="date_error" src="https://cloud.githubusercontent.com/assets/6481056/16813493/51da43e2-494f-11e6-8528-0b778d5a68b9.PNG">
I have referred your test folder example and implemented this

i have used below codes in system config js
map['ng2-datetime-picker'] = 'node_modules/ng2-datetime-picker/dist';
  packages['ng2-datetime-picker'] = {main: 'index.js', defaultExtension: 'js'};

In my component used like this 
 import {DateTimePickerDirective} from "ng2-datetime-picker";

html code:
<input [(ngModel)]="date2" ng2-datetime-picker /><br/> 

`<input [(ngModel)]="date2" ng2-datetime-picker /><br/> `

whenever I tap calendar icon , I am getting below error and calendar displayed partially( the day only displaying)

platform-browser.umd.js:2306 EXCEPTION: Error in ./DateTimePickerComponent class DateTimePickerComponent - inline template:6:11
platform-browser.umd.js:2306 ORIGINAL EXCEPTION: TypeError: Cannot read property 'fullName' of undefined

![image](https://cloud.githubusercontent.com/assets/6481056/16813391/dd5fb0ba-494e-11e6-91ab-085887b4f178.png)

Can you please help me on this

**Comment by allenhwkim** [comment]
It seems your original date in input field is not parsable date. e.g. 'Jan 01 2016'. It seems fine with me with Chrome.  Could you create a plunker example for your issue like this? https://plnkr.co/edit/lbNRAh?p=info

![image](https://cloud.githubusercontent.com/assets/1437734/16815298/3ecaae42-4907-11e6-969a-533fd823a7c6.png)

**Comment by neelsbr** [comment]
Thanks for your reply. I have attached same plunkr screenshot which was taken in chrome & edge. calendar not displayed. I have not changed anything in the example. Please have a look.

<img width="960" alt="date-err" src="https://cloud.githubusercontent.com/assets/6481056/16818206/3a0f30e6-4964-11e6-8a81-2790e308d582.png">
<img width="960" alt="date-err1" src="https://cloud.githubusercontent.com/assets/6481056/16818207/3a121d56-4964-11e6-884b-65a59abe42f8.png">

**Comment by allenhwkim** [comment]
Updated with 0.4.1. Havent' tested with IE.

**Comment by allenhwkim** [comment]
I think this is fixed. Please reopen if not fixed
