### ISSUE TITLE
JS errors when typing text inside calendar

### ISSUE THREAD

**Issue by msaccone** [ng2-ui/ng2-datetime-picker#71]
If accidentally the user starts typing inside the input, the calendar crashes and won't be available again to select a date, until a complete page refresh.
![capture](https://cloud.githubusercontent.com/assets/19209362/20578492/56331d28-b1a6-11e6-98b0-ab41286276c4.PNG)
![capture2](https://cloud.githubusercontent.com/assets/19209362/20578493/5638c084-b1a6-11e6-9035-aef72ae1922e.PNG)

EXCEPTION: Error in ./DateTimePickerComponent class DateTimePickerComponent - inline template:7:12 caused by: Cannot read property 'fullName' of undefinedErrorHandler.handleError @ error_handler.js:45next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:72NgZone.runGuarded @ ng_zone.js:236outsideHandler @ dom_events.js:26ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:47 ORIGINAL EXCEPTION: Cannot read property 'fullName' of undefinedErrorHandler.handleError @ error_handler.js:47next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:72NgZone.runGuarded @ ng_zone.js:236outsideHandler @ dom_events.js:26ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:50 ORIGINAL STACKTRACE:ErrorHandler.handleError @ error_handler.js:50next @ application_ref.js:273schedulerFn @ async.js:82SafeSubscriber.__tryOrUnsub @ Subscriber.js:223SafeSubscriber.next @ Subscriber.js:172Subscriber._next @ Subscriber.js:125Subscriber.next @ Subscriber.js:89Subject.next @ Subject.js:55EventEmitter.emit @ async.js:74onError @ ng_zone.js:120onHandleError @ ng_zone_impl.js:64ZoneDelegate.handleError @ zone.js:207Zone.runGuarded @ zone.js:113NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:72NgZone.runGuarded @ ng_zone.js:236outsideHandler @ dom_events.js:26ZoneDelegate.invokeTask @ zone.js:236Zone.runTask @ zone.js:136ZoneTask.invoke @ zone.js:304
error_handler.js:51 TypeError: Cannot read property 'fullName' of undefined
    at _View_DateTimePickerComponent0.detectChangesInternal (DateTimePickerComponent.ngfactory.js:318)

**Comment by Krisa** [comment]
Can you share a plunkr or compare your code to the plunkr of the Readme: https://plnkr.co/edit/su2aiL ? If you try editing the input you see there (avoid the first one ... :) ), you will see that it works pretty well.

**Comment by msaccone** [comment]
Hi @Krisa, 

Thanks for your answer and examples.

The plunkr doesn't throw an Exception, but all calendars stop working when text is entered manually.
Try two or more times, it doesn't happen at first

Hope these hints helps!

![ng2-datetimepicker](https://cloud.githubusercontent.com/assets/19209362/20598800/a7bc08e8-b229-11e6-935c-1229925c940c.png)

**Comment by Krisa** [comment]
That only appears if you provide a date which cannot be parsed. But typing this manually will for example work:
![image](https://cloud.githubusercontent.com/assets/1253866/20599089/a528788c-b24c-11e6-9947-305f4fe94f56.png)

**Comment by msaccone** [comment]
You're right, but I think the main problem is that if the user **accidentally enters some data that can't be parsed**, then the datetime picker stops working until a full refresh of the page.

**Comment by allenhwkim** [comment]
This error seems solved after re-factoring, but defaulting to the current date. Please make it sure the change is correct.
