### ISSUE TITLE
Custom date format causes range inputs to behave oddly

### ISSUE THREAD

**Issue by lehphyro** [ng2-ui/ng2-datetime-picker#72]
I've set the custom date format from README and now when I have a low time, like 08:30, and click directly on a high time, like 16:30, to make the range selector "jump", it goes back to the previous time.

**Comment by allenhwkim** [comment]
Thanks for reporting this. Could you make a plunker example, meanwhile?

**Comment by allenhwkim** [comment]
Closing it, please verify the changes
