### ISSUE TITLE
Disable some date

### ISSUE THREAD

**Issue by trungk18** [ng2-ui/ng2-datetime-picker#79]
Hi guys,

Thanks for this great library.

Can I check If you are planning to support disabling some date in the picker like the below link?

[https://eonasdan.github.io/bootstrap-datetimepicker/#enableddisabled-dates](https://eonasdan.github.io/bootstrap-datetimepicker/#enableddisabled-dates)

**Comment by allenhwkim** [comment]
Currently, we do not have this feature. I think this can be developed with;

1. `min-date`
2. `max-date`
3. `min-hour`
4. `max-hour`
5. `dates-disabled`

**Comment by allenhwkim** [comment]
released with 0.11.0 please verify the change.
