### ISSUE TITLE
min or max date missing causes "Cannot read property 'getTime' of undefined"

### ISSUE THREAD

**Issue by msaccone** [ng2-ui/ng2-datetime-picker#82]
At datetime-picker.component.js

 DateTimePickerComponent.prototype.isDateDisabled = function (date) {
        var dateInTime = date.getTime();
        **var minDateInTime = this.minDate.getTime();
        var maxDateInTime = this.maxDate.getTime();**

**Comment by allenhwkim** [comment]
Fix is relased with 0.11.1, plz verify the fix

**Comment by msaccone** [comment]
fixed!

**Comment by allenhwkim** [comment]
Thanks for confirming :)
