### ISSUE TITLE
How do I set the control's language

### ISSUE THREAD

**Issue by chendb** [ng2-ui/ng2-datetime-picker#84]
In angular 2 ,How do I set the control's language？

**Comment by allenhwkim** [comment]
A good question. 

You need to have momentjs with locals first,
```
<script src="moment-with-locales.min.js"></script>
```

Secondly, you need to set locale when app starts.
https://plnkr.co/edit/jnR8xnbV7zZioGW66MnN?p=preview

Example, https://plnkr.co/edit/jnR8xnbV7zZioGW66MnN?p=preview
