### ISSUE TITLE
First day of week isn't wokring?

### ISSUE THREAD

**Issue by msaccone** [ng2-ui/ng2-datetime-picker#85]
I've used your plunkr here to test it

https://embed.plnkr.co/jnR8xnbV7zZioGW66MnN/

I've tried first-day-of-week="1" first-day-of-week="2" , ....

With and with out locale..

Always showing Sunday as first day of week

**Comment by allenhwkim** [comment]
Thanks for reporting this. I have made fix and released 0.11.4
please verify the changes
https://plnkr.co/edit/htbExZ?p=preview
