### ISSUE TITLE
Separate displayed date format from returned value

### ISSUE THREAD

**Issue by themastersoda** [ng2-ui/ng2-datetime-picker#86]
Hi, im looking for a way to display date string inside the input in one format, but set model value to a different one. It seems, that now both use the same function to parse date into string. Would it be possible to customize both of those separately?

**Comment by allenhwkim** [comment]
As you see here, https://github.com/ng2-ui/ng2-datetime-picker/blob/master/src/datetime-picker.directive.ts#L206, the element has its `dateValue`, and the value you see is `toString()` method applied. If you want to access please use `dateValue`

**Comment by allenhwkim** [comment]
Please refer to this screenshot.

![image](https://cloud.githubusercontent.com/assets/1437734/21187050/979387f0-c1e4-11e6-8d1d-80ce8c3b9721.png)

https://plnkr.co/edit/ApJNv9?p=preview
