### ISSUE TITLE
Calendar not localized

### ISSUE THREAD

**Issue by negberts** [ng2-ui/ng2-datetime-picker#88]
We have defined the Ng2DatetimePickerModule in a shared module which is imported in the app.module with SharedModule.forRoot()

In the app.component we have defined the locale to be Dutch: moment.locale('nl');

The datepicker shows the date nicely as DD-MM-YYYY and when I log moment.months() in the sub component that uses the DateTimePicker it prints nicely the Dutch months, but the DateTimePicker still shows the months and days in English.  Any ideas what's going wrong here?

**Comment by allenhwkim** [comment]
Could you create a plunker example for this, so that I can see it?

**Comment by negberts** [comment]
I've tried but keep getting an error: https://plnkr.co/edit/aQjSBAgkJzJnxw20rl2G?p=preview 

I probably should add routing there, because that's what happens in our app, we route to the sub module.

**Comment by negberts** [comment]
Updated the plunker.. Problem is it's not going wrong in the plunker :(

**Comment by negberts** [comment]
Wait, it is going wrong... The locale is set in app.component but in the sub.component which is in sub.module the datepicker is not in Dutch.

**Comment by negberts** [comment]
I'm lost...

**Comment by allenhwkim** [comment]
LOL, you can copy French example from README.md

https://github.com/ng2-ui/ng2-datetime-picker
https://plnkr.co/edit/J6hXyB?p=preview

Then change it to Dutch, and see if still working or not.

**Comment by allenhwkim** [comment]
I changed to nl-nl, and it seems working fine to me
![image](https://cloud.githubusercontent.com/assets/1437734/21327334/97577fdc-c5fc-11e6-80e8-8e375f70b9a9.png)

**Comment by negberts** [comment]
I know, but the plunker I created represents our situation better, with shared modules and sub modules. The plunker is correct. It just works, and it doesn't work in our application :(

Maybe some other third party package is messing with moment too. 

But isn't it possible to get some kind of language setting in the datepicker?

**Comment by negberts** [comment]
What is the export of DateTime doing in your French example by the way?

**Comment by negberts** [comment]
I've created a plunker of the French example where moment is included in the system.config.js. Then it goes wrong. Maybe it uses another instance of moment then?

https://plnkr.co/edit/RC92yy9O82BwwNTtBclw?p=preview

**Comment by allenhwkim** [comment]
Difference between your case and my case is the source of momentjs

I am using momentjs from `<script>` tag, and you are using it from `npm`.

I don't know how to use localized momentjs from `npm`. I tried without success. 
As you see in my example, all moment is from window variable, which is not imported.

https://plnkr.co/edit/9NKp9g?p=preview

**Comment by negberts** [comment]
Maybe you could make the initialize method static/public so it can be called to re-initialize? Or add an overload which takes moment variable?

something like:

static reInitialize(moment: any)
{
/**
     * if momentjs is available, use momentjs localized months, week, etc.
     */

    if (typeof moment !== 'undefined') {
       this.months = this.months.map( function(el, index) {
        el.fullName = moment.months()[index];
        el.shortName = moment.monthsShort()[index];
        return el;
      });

      this.daysOfWeek = this.daysOfWeek.map( function(el, index) {
        el.fullName = moment.weekdays()[index];
        el.shortName = moment.weekdaysShort()[index].substr(0,2);
        return el;
      });
      this.firstDayOfWeek = moment.localeData().firstDayOfWeek();
    }

    this.firstDayOfWeek = this.firstDayOfWeek || 0;
    if (Ng2Datetime.customFirstDayOfWeek !== undefined) {
      this.firstDayOfWeek = Ng2Datetime.customFirstDayOfWeek;
    }

    this.localizedDaysOfWeek = this.daysOfWeek
      .concat(this.daysOfWeek)
      .splice(this.firstDayOfWeek, 7);
}

**Comment by allenhwkim** [comment]
@negberts I will think about it, Meanwhile, PR would be welcome.

**Comment by allenhwkim** [comment]
This has been updated with version 0.12.1, please follow README.md and verify the changes.

**Comment by negberts** [comment]
How should I be able to use it? Since the variables are static I would expect to be able to use it like this:

 constructor() {
        Ng2DateTime.daysOfWeek = [
            { fullName: 'Zondag', shortName: 'Zon', weekend: true },
            { fullName: 'Maandag', shortName: 'Maa' },
            { fullName: 'Dinsdag', shortName: 'Din' },
            { fullName: 'Woensdag', shortName: 'Woe' },
            { fullName: 'Donderdag', shortName: 'Don' },
            { fullName: 'Vrijdag', shortName: 'Vrij' },
            { fullName: 'Zaterdag', shortName: 'Zat', weekend: true }
        ];
    }

But I receive an error: Ng2DateTime is undefined.

**Comment by allenhwkim** [comment]
Please try `Ng2Datetime`, not `Ng2DateTime`

**Comment by negberts** [comment]
Duh. Works brilliant :)

**Comment by allenhwkim** [comment]
ok, closing it
