### ISSUE TITLE
Example Plunkr is not working

### ISSUE THREAD

**Issue by tom10271** [ng2-ui/ng2-datetime-picker#89]
https://embed.plnkr.co/lbNRAh/

**Comment by allenhwkim** [comment]
I don't know how you get that. The example in readme is this. https://plnkr.co/edit/su2aiL?p=preview

**Comment by tom10271** [comment]
Go to: https://github.com/ng2-ui/ng2-datetime-picker then click `Plunker Example`

Inside the plunkr, there is a link to https://embed.plnkr.co/lbNRAh/. Maybe you need to update the README.md?

**Comment by allenhwkim** [comment]
I think your contents are cached ones
![image](https://cloud.githubusercontent.com/assets/1437734/21377874/ddebef78-c70f-11e6-8ec2-5a4c88cfac26.png)
