### ISSUE TITLE
the module should provide a change event interface

### ISSUE THREAD

**Issue by lzm420241** [ng2-ui/ng2-datetime-picker#90]
when i add change event in input element by using the module, i find the change event did not work! i guess the module had listened the change event.

**Comment by allenhwkim** [comment]
You should use `ngModelChange` instead of `change` because it does not manually invoke `change` event because it is changed by program not manually.

https://plnkr.co/edit/spamdZ?p=preview

**Comment by lzm420241** [comment]
for first time , it has been triggered ngModelChange if you init model data!

**Comment by allenhwkim** [comment]
@lzm420241 that's angular2 behaviour. I can't do much about it. You can raise that issue at stackoverflow or angular2 github.
