### ISSUE TITLE
In Form 24 hr format doesnot work. 

### ISSUE THREAD

**Issue by pksatish07** [ng2-ui/ng2-datetime-picker#92]
When hour is selected above 12 it selects equivalent 12 hr time
<form [formGroup]="myForm">
     <input 
       required
       [(ngModel)]='myVar' hour='23' minute='59'
       formControlName="date" 
       ng2-datetime-picker
       date-format="DD-MM-YYYY hh:mm" close-on-select="false"/>
   </form>

**Comment by allenhwkim** [comment]
You should use HH instead of hh as described in MomentJS dodument

![image](https://cloud.githubusercontent.com/assets/1437734/21524485/6c23d2ea-cce4-11e6-8f3e-53377ebb6fba.png)
