### ISSUE TITLE
How we do with using glyphicon uregent please help where we put  ng2-datetime-picker . 

### ISSUE THREAD

**Issue by ashwinirajput** [ng2-ui/ng2-datetime-picker#95]
```
<div class="form-inline">
    <div  class="input-group date">
        <input class="form-control" # type="text" placeholder="Choose date"   ng2-datetime-picker  date-only="true">
        <div class="input-group-addon" style="">
            <span  class="glyphicon glyphicon-th"></span>
        </div>
    </div>
</div>
```

**Comment by ashwinirajput** [comment]
<div class="form-inline">
                        <div  class="input-group date">
                        <input class="form-control ng-untouched ng-pristine ng-valid" # type="text" placeholder="Choose date"   ng2-datetime-picker  date-only="true">
                        <div class="input-group-addon" style="">
                        <span  class="glyphicon glyphicon-th"></span>
                        </div>
                        </div>
                      </div>

**Comment by allenhwkim** [comment]
First of all, your question is unclear to me. Please create a plunker example or any other example to illustrate, I say illustrate, your issue. 
Without seeing it, I do not understand your problem.

**Comment by ashwinirajput** [comment]
ng2-datetime-picker  with icon I wanted to do but its take only from a text when I click on text how we do with the icon.when I click on the icon then the date will be displayed in text.

 <div class="form-inline">
                        <div  class="input-group date">
                        <input class="form-control ng-untouched ng-pristine ng-valid" type="text"     placeholder="Choose date"   ng2-datetime-picker  date-only="true">
                        <div class="input-group-addon" style="">
                        <span class="glyphicon glyphicon-th"></span>
                        </div>
                        </div>
                      </div>

**Comment by allenhwkim** [comment]
It was hard to understand your question.

I assume that you want to click an icon, then you want to see datetime picker.
If so, you can simply  add `(click)` function to your glyphicon that triggers `click` of your input field

a working example is here:  https://plnkr.co/edit/osIhs8?p=preview

**Comment by lakshmipunati** [comment]
Hi,

This plunker example is not working,can you check that once.

https://plnkr.co/edit/osIhs8?p=preview
