### ISSUE TITLE
how to use date-format="date" instead of date-format="MM/DD/YYYY"

### ISSUE THREAD

**Issue by githubServic** [ng2-ui/ng2-datetime-picker#97]
Thanks for great datetime-picker. it works like magic. so i wanted to customize date-format so that i can use in more readable way like use  date-format="date"  instead of date-format="MM/DD/YYYY". so date literally means MM/DD/YYYY. how do i do that ?

**Comment by allenhwkim** [comment]
Do you mean `[date-format]="date"`?
